version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pwd
    volumes:
      - data:/var/lib/postgresql/data
      - sql:/var/lib/postgresql/sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin-pwd
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  sql:
  pgadmin-data: